"""
High-level paper-analysis orchestration for the AI Research Paper Assistant.

Responsibilities
----------------
This module receives the already-selected papers from research/search.py and
coordinates the seven analysis modules:

    summary
    model
    dataset
    methodology
    findings
    strengths
    weaknesses

It deliberately does NOT:
- retrieve papers
- call FAISS/SPECTER2
- rerank or sort papers
- load the corpus
- load PDFs
- perform OCR/chunking
- implement RAG/Q&A
- instantiate a direct LLM client
- duplicate analysis logic from backend/analysis/

The injected analysis modules own extraction/generation logic.

The service is designed to be resilient at the paper level: one malformed or
failed paper produces an explicit failed/partial result rather than silently
destroying the other analyses.
"""

from __future__ import annotations

import logging
import math
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Mapping, Optional, Protocol, Sequence

logger = logging.getLogger(__name__)

UNAVAILABLE_TEXT = "Not available in the provided content."
UNDETERMINABLE_TEXT = (
    "Cannot be reliably determined from the available content."
)
DEFAULT_ANALYSIS_MODE = "abstract"


# ============================================================================
# Exceptions
# ============================================================================


class PaperAnalysisError(RuntimeError):
    """Base exception for high-level paper-analysis failures."""


class InvalidPaperError(PaperAnalysisError, ValueError):
    """Raised when an input paper violates the analyzer contract."""


class AnalysisValidationError(PaperAnalysisError, ValueError):
    """Raised when an analysis module returns malformed output."""


class EvidenceValidationError(PaperAnalysisError, ValueError):
    """Raised when an evidence-bearing result violates evidence rules."""


# ============================================================================
# Status / evidence models
# ============================================================================


class AnalysisStatus(str, Enum):
    """Per-paper analysis status."""

    SUCCESS = "success"
    PARTIAL = "partial"
    FAILED = "failed"


class Confidence(str, Enum):
    """
    Qualitative extraction confidence.

    This is extraction certainty, NOT scientific truth and NOT a calibrated
    probability.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass(frozen=True)
class Evidence:
    """Source-grounding information attached to an analytical claim."""

    text: str
    source: str = "provided_content"
    confidence: Confidence = Confidence.MEDIUM

    def __post_init__(self) -> None:
        if not isinstance(self.text, str) or not self.text.strip():
            raise EvidenceValidationError(
                "Evidence text must be a non-empty string."
            )

        if not isinstance(self.source, str) or not self.source.strip():
            raise EvidenceValidationError(
                "Evidence source must be a non-empty string."
            )

        if not isinstance(self.confidence, Confidence):
            raise EvidenceValidationError(
                "Evidence confidence must be a Confidence enum value."
            )


@dataclass(frozen=True)
class AnalysisField:
    """
    Generic structured analysis field.

    value can be a string, list, mapping, scalar, or None depending on the
    injected analysis module's schema. evidence is optional because some
    existing modules may not expose evidence yet; the orchestrator never
    fabricates it.
    """

    value: Any
    evidence: tuple[Evidence, ...] = ()
    confidence: Optional[Confidence] = None

    def __post_init__(self) -> None:
        if self.confidence is not None and not isinstance(
            self.confidence, Confidence
        ):
            raise AnalysisValidationError(
                "AnalysisField.confidence must be a Confidence enum."
            )

        for item in self.evidence:
            if not isinstance(item, Evidence):
                raise AnalysisValidationError(
                    "AnalysisField.evidence contains an invalid item."
                )


@dataclass(frozen=True)
class PaperAnalysis:
    """
    Structured analysis for one selected research paper.

    Metadata is preserved from search.py and is never regenerated by this
    service.
    """

    document_id: str
    rank: int
    title: str

    summary: Any
    model: Any
    dataset: Any
    methodology: Any
    findings: Any
    strengths: Any
    weaknesses: Any

    status: AnalysisStatus = AnalysisStatus.SUCCESS
    error_message: Optional[str] = None

    authors: Any = None
    published_date: Any = None
    category: Any = None
    retrieval_score: Any = None
    reranker_score: Any = None
    final_score: Any = None

    evidence: tuple[Evidence, ...] = ()
    component_status: Mapping[str, str] = field(default_factory=dict)
    analysis_mode: str = DEFAULT_ANALYSIS_MODE
    latency_seconds: Optional[float] = None

    def __post_init__(self) -> None:
        if not self.document_id.strip():
            raise InvalidPaperError(
                "PaperAnalysis.document_id cannot be empty."
            )

        if self.rank <= 0:
            raise InvalidPaperError(
                "PaperAnalysis.rank must be positive."
            )

        if not self.title.strip():
            raise InvalidPaperError(
                "PaperAnalysis.title cannot be empty."
            )

        if self.status == AnalysisStatus.SUCCESS and self.error_message:
            raise AnalysisValidationError(
                "Successful PaperAnalysis cannot contain error_message."
            )

        if self.status != AnalysisStatus.SUCCESS and not self.error_message:
            raise AnalysisValidationError(
                "Partial/failed PaperAnalysis requires error_message."
            )


@dataclass(frozen=True)
class ResearchAnalysisResponse:
    """Structured response containing paper analyses in original rank order."""

    query: str
    analyzed_count: int
    papers: list[PaperAnalysis]
    requested_count: int = 0
    failed_count: int = 0
    partial_count: int = 0
    total_latency_seconds: Optional[float] = None

    def __post_init__(self) -> None:
        if self.analyzed_count != len(self.papers):
            raise AnalysisValidationError(
                "analyzed_count does not match papers length."
            )

        if self.failed_count < 0 or self.partial_count < 0:
            raise AnalysisValidationError(
                "Failure counters cannot be negative."
            )


# ============================================================================
# Dependency protocols
# ============================================================================


class AnalysisModuleProtocol(Protocol):
    """
    Flexible protocol for injected analysis modules.

    Supported implementations may expose:
        analyze(paper)
        analyze(paper=paper)
        extract(paper)
        run(paper)

    The orchestrator resolves the supported method without implementing the
    actual analysis logic.
    """

    def analyze(self, paper: Any) -> Any:
        ...


# ============================================================================
# Input helpers
# ============================================================================


def _get(paper: Any, key: str, default: Any = None) -> Any:
    """Read a field from either a mapping or an object."""
    if isinstance(paper, Mapping):
        return paper.get(key, default)

    return getattr(paper, key, default)


def _first_non_empty(
    paper: Any,
    keys: Sequence[str],
    default: Any = None,
) -> Any:
    """Return the first non-empty field among aliases."""
    for key in keys:
        value = _get(paper, key, None)

        if value is None:
            continue

        if isinstance(value, str) and not value.strip():
            continue

        return value

    return default


def _normalize_text(value: Any) -> Optional[str]:
    """Normalize a text-like value without inventing content."""
    if value is None:
        return None

    if isinstance(value, str):
        text = value.strip()
        return text or None

    return str(value).strip() or None


def _paper_content(paper: Any) -> str:
    """
    Collect only content that is already attached to the selected paper.

    No filesystem lookup or dataset reload occurs.
    """
    parts: list[str] = []

    title = _normalize_text(
        _first_non_empty(paper, ("title",), None)
    )
    if title:
        parts.append(f"Title: {title}")

    abstract = _normalize_text(
        _first_non_empty(
            paper,
            ("abstract", "summary", "text", "content"),
            None,
        )
    )
    if abstract:
        parts.append(f"Abstract: {abstract}")

    # Full text is accepted only if already present on the object.
    full_text = _normalize_text(
        _first_non_empty(
            paper,
            ("full_text", "paper_text", "body"),
            None,
        )
    )
    if full_text and full_text != abstract:
        parts.append(f"Full text: {full_text}")

    return "\n\n".join(parts)


def _validate_paper_input(paper: Any, position: int) -> dict[str, Any]:
    """Validate and normalize the minimum paper contract."""
    if paper is None:
        raise InvalidPaperError(
            f"Paper at input position {position} is None."
        )

    document_id = _normalize_text(
        _first_non_empty(
            paper,
            ("document_id", "id", "paper_id"),
            None,
        )
    )

    if not document_id:
        raise InvalidPaperError(
            f"Paper at input position {position} has no document_id."
        )

    title = _normalize_text(
        _first_non_empty(
            paper,
            ("title",),
            None,
        )
    )

    if not title:
        raise InvalidPaperError(
            f"Paper {document_id!r} has no title."
        )

    rank = _get(paper, "rank", None)

    if isinstance(rank, bool) or not isinstance(rank, int) or rank <= 0:
        raise InvalidPaperError(
            f"Paper {document_id!r} has invalid rank={rank!r}."
        )

    content = _paper_content(paper)

    return {
        "document_id": document_id,
        "rank": rank,
        "title": title,
        "authors": _get(paper, "authors"),
        "published_date": _get(paper, "published_date"),
        "category": _get(paper, "category"),
        "retrieval_score": _get(paper, "retrieval_score"),
        "reranker_score": _get(paper, "reranker_score"),
        "final_score": _get(paper, "final_score"),
        "content": content,
        "has_abstract": bool(
            _normalize_text(
                _first_non_empty(
                    paper,
                    ("abstract", "summary"),
                    None,
                )
            )
        ),
        "has_full_text": bool(
            _normalize_text(
                _first_non_empty(
                    paper,
                    ("full_text", "paper_text", "body"),
                    None,
                )
            )
        ),
    }


def _validate_score(
    value: Any,
    *,
    field_name: str,
    document_id: str,
) -> Any:
    """Validate scores when supplied, without changing their semantics."""
    if value is None:
        return None

    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise InvalidPaperError(
            f"Paper {document_id!r} has invalid {field_name}={value!r}."
        )

    if not math.isfinite(float(value)):
        raise InvalidPaperError(
            f"Paper {document_id!r} has non-finite "
            f"{field_name}={value!r}."
        )

    return value


# ============================================================================
# Module invocation / result normalization
# ============================================================================


def _invoke_module(
    module: Any,
    *,
    paper: Any,
    field_name: str,
) -> Any:
    """
    Invoke an injected analysis component using a small, explicit interface
    compatibility layer.

    The analyzer does not contain extraction logic; it only calls the
    injected component.
    """
    if module is None:
        raise AnalysisValidationError(
            f"Analysis module for {field_name!r} is not configured."
        )

    method = None

    for method_name in ("analyze", "extract", "run"):
        candidate = getattr(module, method_name, None)
        if callable(candidate):
            method = candidate
            break

    if method is None and callable(module):
        method = module

    if method is None:
        raise AnalysisValidationError(
            f"Analysis module for {field_name!r} does not expose a "
            "supported callable interface."
        )

    try:
        return method(paper)
    except TypeError as first_error:
        # Support modules implemented as analyze(paper=...).
        try:
            return method(paper=paper)
        except TypeError:
            raise first_error


def _normalize_analysis_result(
    result: Any,
    *,
    field_name: str,
) -> Any:
    """
    Validate a module result without forcing a single schema on all existing
    analysis modules.

    Structured mappings/lists/strings are preserved as supplied.
    """
    if result is None:
        return UNAVAILABLE_TEXT

    if isinstance(result, (str, int, float, bool)):
        return result

    if isinstance(result, Mapping):
        return dict(result)

    if isinstance(result, (list, tuple)):
        return list(result)

    # Dataclass / Pydantic / custom result objects are preserved. They are
    # intentionally not converted through arbitrary reflection.
    return result


def _result_contains_evidence(result: Any) -> bool:
    """Detect explicit evidence without inventing any."""
    if isinstance(result, Evidence):
        return True

    if isinstance(result, AnalysisField):
        return bool(result.evidence)

    if isinstance(result, Mapping):
        evidence = result.get("evidence")
        return bool(evidence)

    return bool(getattr(result, "evidence", None))


def _validate_component_result(
    result: Any,
    *,
    field_name: str,
    content_available: bool,
) -> Any:
    """
    Validate the basic shape of one analysis result.

    The analyzer intentionally does not claim a field is unavailable merely
    because the module returned a value. Evidence validation is delegated to
    the component's own structured output where available.
    """
    normalized = _normalize_analysis_result(
        result,
        field_name=field_name,
    )

    if isinstance(normalized, Mapping):
        if "confidence" in normalized:
            confidence = normalized["confidence"]

            if isinstance(confidence, str):
                if confidence.lower() not in {
                    item.value for item in Confidence
                }:
                    raise AnalysisValidationError(
                        f"{field_name} returned invalid confidence="
                        f"{confidence!r}."
                    )

        if "evidence" in normalized:
            evidence = normalized["evidence"]

            if evidence is not None and not isinstance(
                evidence,
                (list, tuple),
            ):
                raise AnalysisValidationError(
                    f"{field_name}.evidence must be a list/tuple."
                )

            if evidence:
                for item in evidence:
                    if isinstance(item, Evidence):
                        continue

                    if not isinstance(item, Mapping):
                        raise AnalysisValidationError(
                            f"{field_name}.evidence contains malformed "
                            "items."
                        )

                    text = item.get("text")
                    source = item.get("source", "provided_content")

                    if not isinstance(text, str) or not text.strip():
                        raise EvidenceValidationError(
                            f"{field_name}.evidence item has no text."
                        )

                    if not isinstance(source, str) or not source.strip():
                        raise EvidenceValidationError(
                            f"{field_name}.evidence item has no source."
                        )

    # Empty content is valid only when explicitly represented by the
    # unavailable marker. We never fabricate a replacement claim.
    if not content_available and normalized not in (
        None,
        UNAVAILABLE_TEXT,
        UNDETERMINABLE_TEXT,
    ):
        logger.warning(
            "%s returned analysis despite no paper content being "
            "available; verify that the injected module uses its own "
            "grounding contract.",
            field_name,
        )

    return normalized


def _component_status_value(
    result: Any,
) -> str:
    """Infer a compact component status without altering the result."""
    if isinstance(result, Mapping):
        status = result.get("status")

        if isinstance(status, str) and status.strip():
            return status.strip().lower()

    return "success"


# ============================================================================
# Analyzer
# ============================================================================


class ResearchPaperAnalyzer:
    """
    High-level Top-K paper-analysis orchestrator.

    Parameters
    ----------
    summary_analyzer
        Existing summary analysis component.
    model_analyzer
        Existing model extraction component.
    dataset_analyzer
        Existing dataset extraction component.
    methodology_analyzer
        Existing methodology analysis component.
    findings_analyzer
        Existing findings extraction component.
    strengths_analyzer
        Existing evidence-grounded strengths component.
    weaknesses_analyzer
        Existing evidence-grounded weaknesses component.
    analysis_mode
        "abstract" or "full_text". This is metadata/configuration only; the
        service never loads the underlying content itself.
    """

    COMPONENTS = (
        "summary",
        "model",
        "dataset",
        "methodology",
        "findings",
        "strengths",
        "weaknesses",
    )

    def __init__(
        self,
        *,
        summary_analyzer: Any,
        model_analyzer: Any,
        dataset_analyzer: Any,
        methodology_analyzer: Any,
        findings_analyzer: Any,
        strengths_analyzer: Any,
        weaknesses_analyzer: Any,
        analysis_mode: str = DEFAULT_ANALYSIS_MODE,
    ) -> None:
        if analysis_mode not in {"abstract", "full_text"}:
            raise ValueError(
                "analysis_mode must be 'abstract' or 'full_text'."
            )

        self._modules = {
            "summary": summary_analyzer,
            "model": model_analyzer,
            "dataset": dataset_analyzer,
            "methodology": methodology_analyzer,
            "findings": findings_analyzer,
            "strengths": strengths_analyzer,
            "weaknesses": weaknesses_analyzer,
        }

        missing = [
            name
            for name, module in self._modules.items()
            if module is None
        ]

        if missing:
            raise ValueError(
                "Missing required analysis dependencies: "
                + ", ".join(missing)
            )

        self.analysis_mode = analysis_mode

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze_paper(
        self,
        paper: Any,
    ) -> PaperAnalysis:
        """Analyze exactly one selected paper."""
        started = time.perf_counter()

        normalized = _validate_paper_input(
            paper,
            position=0,
        )

        document_id = normalized["document_id"]
        rank = normalized["rank"]
        title = normalized["title"]
        content_available = bool(normalized["content"])

        logger.debug(
            "Analyzing paper rank=%d document_id=%s.",
            rank,
            document_id,
        )

        results: dict[str, Any] = {}
        component_status: dict[str, str] = {}
        errors: list[str] = []
        evidence: list[Evidence] = []

        # Required analysis order from the project contract.
        for field_name in self.COMPONENTS:
            module = self._modules[field_name]

            try:
                raw_result = _invoke_module(
                    module,
                    paper=paper,
                    field_name=field_name,
                )

                result = _validate_component_result(
                    raw_result,
                    field_name=field_name,
                    content_available=content_available,
                )

                results[field_name] = result
                component_status[field_name] = (
                    _component_status_value(result)
                )

                evidence.extend(
                    self._extract_evidence(
                        result,
                        field_name=field_name,
                    )
                )

                logger.debug(
                    "%s analysis completed for document_id=%s.",
                    field_name,
                    document_id,
                )

            except Exception as exc:
                # Failure isolation: one component failure should not destroy
                # the other component results.
                errors.append(
                    f"{field_name}: {type(exc).__name__}: {exc}"
                )
                component_status[field_name] = "failed"
                results[field_name] = UNDETERMINABLE_TEXT

                logger.exception(
                    "Paper analysis component failed: "
                    "document_id=%s component=%s.",
                    document_id,
                    field_name,
                )

        failed_components = [
            name
            for name, status in component_status.items()
            if status == "failed"
        ]

        if len(failed_components) == len(self.COMPONENTS):
            status = AnalysisStatus.FAILED
            error_message = (
                "All paper-analysis components failed. "
                + " | ".join(errors)
            )
        elif failed_components or any(
            value in {"partial", "warning"}
            for value in component_status.values()
        ):
            status = AnalysisStatus.PARTIAL
            error_message = " | ".join(errors) if errors else (
                "Some analysis components returned partial results."
            )
        else:
            status = AnalysisStatus.SUCCESS
            error_message = None

        latency = time.perf_counter() - started

        return PaperAnalysis(
            document_id=document_id,
            rank=rank,
            title=title,
            summary=results["summary"],
            model=results["model"],
            dataset=results["dataset"],
            methodology=results["methodology"],
            findings=results["findings"],
            strengths=results["strengths"],
            weaknesses=results["weaknesses"],
            status=status,
            error_message=error_message,
            authors=normalized["authors"],
            published_date=normalized["published_date"],
            category=normalized["category"],
            retrieval_score=_validate_score(
                normalized["retrieval_score"],
                field_name="retrieval_score",
                document_id=document_id,
            ),
            reranker_score=_validate_score(
                normalized["reranker_score"],
                field_name="reranker_score",
                document_id=document_id,
            ),
            final_score=_validate_score(
                normalized["final_score"],
                field_name="final_score",
                document_id=document_id,
            ),
            evidence=tuple(evidence),
            component_status=dict(component_status),
            analysis_mode=self.analysis_mode,
            latency_seconds=latency,
        )

    def analyze(
        self,
        search_response: Any,
    ) -> ResearchAnalysisResponse:
        """
        Analyze the already-selected papers from search.py.

        Paper order is preserved exactly as supplied. No ranking/relevance
        modification is performed.
        """
        started = time.perf_counter()

        query, papers = self._extract_search_response(
            search_response
        )

        if not papers:
            logger.info(
                "Starting analysis of Top 0 papers."
            )

            return ResearchAnalysisResponse(
                query=query,
                analyzed_count=0,
                papers=[],
                requested_count=0,
                failed_count=0,
                partial_count=0,
                total_latency_seconds=(
                    time.perf_counter() - started
                ),
            )

        logger.info(
            "Starting analysis of Top %d papers.",
            len(papers),
        )

        normalized_papers = self._validate_paper_collection(
            papers
        )

        analyses: list[PaperAnalysis] = []
        seen_ids: set[str] = set()

        for position, paper in enumerate(
            normalized_papers
        ):
            document_id = _normalize_text(
                _first_non_empty(
                    paper,
                    ("document_id", "id", "paper_id"),
                    None,
                )
            )

            if document_id in seen_ids:
                # Duplicate IDs are a pipeline anomaly. Do not silently
                # analyze the same paper twice.
                analyses.append(
                    self._failed_paper(
                        paper=paper,
                        error_message=(
                            "Duplicate document_id encountered in the "
                            "selected paper list; analysis skipped."
                        ),
                        position=position,
                    )
                )
                continue

            seen_ids.add(document_id or "")

            try:
                analysis = self.analyze_paper(paper)

            except Exception as exc:
                # Paper-level isolation.
                logger.exception(
                    "Paper analysis failed at position=%d "
                    "document_id=%s.",
                    position,
                    document_id,
                )

                analysis = self._failed_paper(
                    paper=paper,
                    error_message=(
                        f"{type(exc).__name__}: {exc}"
                    ),
                    position=position,
                )

            analyses.append(analysis)

        failed_count = sum(
            item.status == AnalysisStatus.FAILED
            for item in analyses
        )
        partial_count = sum(
            item.status == AnalysisStatus.PARTIAL
            for item in analyses
        )

        total_latency = time.perf_counter() - started

        logger.info(
            "Paper analysis completed: total=%d, partial=%d, failed=%d, "
            "latency=%.4fs.",
            len(analyses),
            partial_count,
            failed_count,
            total_latency,
        )

        return ResearchAnalysisResponse(
            query=query,
            analyzed_count=len(analyses),
            papers=analyses,
            requested_count=len(normalized_papers),
            failed_count=failed_count,
            partial_count=partial_count,
            total_latency_seconds=total_latency,
        )

    # ------------------------------------------------------------------
    # Input handling
    # ------------------------------------------------------------------

    def _extract_search_response(
        self,
        search_response: Any,
    ) -> tuple[str, list[Any]]:
        if search_response is None:
            raise InvalidPaperError(
                "search_response cannot be None."
            )

        query = _normalize_text(
            _get(search_response, "query", "")
        )

        if not query:
            raise InvalidPaperError(
                "search_response.query must be a non-empty string."
            )

        papers = _get(search_response, "results", None)

        if papers is None:
            papers = _get(search_response, "papers", None)

        if papers is None:
            raise InvalidPaperError(
                "search_response must expose results or papers."
            )

        if isinstance(papers, (str, bytes)):
            raise InvalidPaperError(
                "search_response papers/results must be a sequence."
            )

        try:
            return query, list(papers)
        except TypeError as exc:
            raise InvalidPaperError(
                "search_response papers/results must be iterable."
            ) from exc

    def _validate_paper_collection(
        self,
        papers: Sequence[Any],
    ) -> list[Any]:
        """Validate collection-level invariants without reordering."""
        if len(papers) > 0:
            ranks: list[int] = []

            for position, paper in enumerate(papers):
                normalized = _validate_paper_input(
                    paper,
                    position=position,
                )

                ranks.append(normalized["rank"])

                for score_name in (
                    "retrieval_score",
                    "reranker_score",
                    "final_score",
                ):
                    _validate_score(
                        normalized[score_name],
                        field_name=score_name,
                        document_id=normalized["document_id"],
                    )

            # Search.py owns final ordering. Analyzer only checks that the
            # input ranks are internally coherent; it never changes them.
            if len(set(ranks)) != len(ranks):
                raise InvalidPaperError(
                    "Selected papers contain duplicate ranks."
                )

        return list(papers)

    # ------------------------------------------------------------------
    # Evidence extraction
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_evidence(
        result: Any,
        *,
        field_name: str,
    ) -> list[Evidence]:
        """
        Preserve evidence supplied by analysis modules.

        This method never invents source text.
        """
        raw_evidence: Any = None

        if isinstance(result, Evidence):
            return [result]

        if isinstance(result, AnalysisField):
            return list(result.evidence)

        if isinstance(result, Mapping):
            raw_evidence = result.get("evidence")
        else:
            raw_evidence = getattr(
                result,
                "evidence",
                None,
            )

        if not raw_evidence:
            return []

        output: list[Evidence] = []

        for item in raw_evidence:
            if isinstance(item, Evidence):
                output.append(item)
                continue

            if not isinstance(item, Mapping):
                raise EvidenceValidationError(
                    f"{field_name}.evidence contains a malformed item."
                )

            text = item.get("text")
            source = item.get(
                "source",
                "provided_content",
            )
            confidence_raw = item.get(
                "confidence",
                Confidence.MEDIUM.value,
            )

            if not isinstance(text, str) or not text.strip():
                raise EvidenceValidationError(
                    f"{field_name}.evidence text is empty."
                )

            if not isinstance(source, str) or not source.strip():
                raise EvidenceValidationError(
                    f"{field_name}.evidence source is empty."
                )

            try:
                confidence = (
                    confidence_raw
                    if isinstance(
                        confidence_raw,
                        Confidence,
                    )
                    else Confidence(
                        str(confidence_raw).lower()
                    )
                )
            except ValueError as exc:
                raise EvidenceValidationError(
                    f"{field_name}.evidence has invalid confidence="
                    f"{confidence_raw!r}."
                ) from exc

            output.append(
                Evidence(
                    text=text.strip(),
                    source=source.strip(),
                    confidence=confidence,
                )
            )

        return output

    # ------------------------------------------------------------------
    # Failure result
    # ------------------------------------------------------------------

    def _failed_paper(
        self,
        *,
        paper: Any,
        error_message: str,
        position: int,
    ) -> PaperAnalysis:
        """Build a safe, explicit failed-paper result."""
        try:
            normalized = _validate_paper_input(
                paper,
                position=position,
            )
        except Exception:
            # The input itself is malformed. Preserve a deterministic,
            # non-fabricated fallback identity for the response.
            document_id = (
                _normalize_text(
                    _first_non_empty(
                        paper,
                        ("document_id", "id", "paper_id"),
                        None,
                    )
                )
                or f"invalid-paper-{position + 1}"
            )

            title = (
                _normalize_text(
                    _first_non_empty(
                        paper,
                        ("title",),
                        None,
                    )
                )
                or UNAVAILABLE_TEXT
            )

            rank = _get(paper, "rank", position + 1)

            if (
                isinstance(rank, bool)
                or not isinstance(rank, int)
                or rank <= 0
            ):
                rank = position + 1

            return PaperAnalysis(
                document_id=document_id,
                rank=rank,
                title=title,
                summary=UNDETERMINABLE_TEXT,
                model=UNAVAILABLE_TEXT,
                dataset=UNAVAILABLE_TEXT,
                methodology=UNAVAILABLE_TEXT,
                findings=UNAVAILABLE_TEXT,
                strengths=UNDETERMINABLE_TEXT,
                weaknesses=UNDETERMINABLE_TEXT,
                status=AnalysisStatus.FAILED,
                error_message=error_message,
                analysis_mode=self.analysis_mode,
            )

        return PaperAnalysis(
            document_id=normalized["document_id"],
            rank=normalized["rank"],
            title=normalized["title"],
            summary=UNDETERMINABLE_TEXT,
            model=UNAVAILABLE_TEXT,
            dataset=UNAVAILABLE_TEXT,
            methodology=UNAVAILABLE_TEXT,
            findings=UNAVAILABLE_TEXT,
            strengths=UNDETERMINABLE_TEXT,
            weaknesses=UNDETERMINABLE_TEXT,
            status=AnalysisStatus.FAILED,
            error_message=error_message,
            authors=normalized["authors"],
            published_date=normalized["published_date"],
            category=normalized["category"],
            retrieval_score=normalized["retrieval_score"],
            reranker_score=normalized["reranker_score"],
            final_score=normalized["final_score"],
            analysis_mode=self.analysis_mode,
        )


# ============================================================================
# Model-free self-test
# ============================================================================


def run_self_test() -> None:
    """Run service-level tests without LLM, GPU, FAISS, or external files."""

    @dataclass(frozen=True)
    class MockModule:
        name: str
        result_factory: Callable[[Any], Any]

        def analyze(self, paper: Any) -> Any:
            return self.result_factory(paper)

    def evidence_result(
        field_name: str,
        value: Any,
    ) -> dict[str, Any]:
        return {
            "value": value,
            "evidence": [
                {
                    "text": (
                        f"Explicit evidence for {field_name} "
                        "from provided abstract."
                    ),
                    "source": "abstract",
                    "confidence": "high",
                }
            ],
            "confidence": "high",
        }

    modules = {
        name: MockModule(
            name=name,
            result_factory=lambda paper, n=name: evidence_result(
                n,
                {
                    "summary": "Paper content supported result."
                },
            ),
        )
        for name in ResearchPaperAnalyzer.COMPONENTS
    }

    analyzer = ResearchPaperAnalyzer(
        summary_analyzer=modules["summary"],
        model_analyzer=modules["model"],
        dataset_analyzer=modules["dataset"],
        methodology_analyzer=modules["methodology"],
        findings_analyzer=modules["findings"],
        strengths_analyzer=modules["strengths"],
        weaknesses_analyzer=modules["weaknesses"],
        analysis_mode="abstract",
    )

    # ------------------------------------------------------------------
    # 1. Single valid paper
    # ------------------------------------------------------------------
    paper = {
        "document_id": "123",
        "rank": 1,
        "title": "Deep Learning for Medical Image Segmentation",
        "authors": ["Author A"],
        "published_date": "2026-01-01",
        "category": "cs.CV",
        "summary": (
            "This paper proposes a supervised segmentation method "
            "and reports experimental results."
        ),
        "retrieval_score": 0.80,
        "reranker_score": 0.92,
        "final_score": 0.92,
    }

    result = analyzer.analyze_paper(paper)

    assert result.document_id == "123"
    assert result.rank == 1
    assert result.title == (
        "Deep Learning for Medical Image Segmentation"
    )
    assert result.status == AnalysisStatus.SUCCESS
    assert result.authors == ["Author A"]
    assert result.final_score == 0.92
    assert len(result.evidence) == 7

    # ------------------------------------------------------------------
    # 2. Top-3 rank preservation
    # ------------------------------------------------------------------
    response = analyzer.analyze(
        {
            "query": "medical image segmentation",
            "candidate_count": 3,
            "result_count": 3,
            "results": [
                paper,
                {
                    **paper,
                    "document_id": "124",
                    "rank": 2,
                    "title": "Paper Two",
                },
                {
                    **paper,
                    "document_id": "125",
                    "rank": 3,
                    "title": "Paper Three",
                },
            ],
        }
    )

    assert response.analyzed_count == 3
    assert [p.document_id for p in response.papers] == [
        "123",
        "124",
        "125",
    ]
    assert [p.rank for p in response.papers] == [1, 2, 3]
    assert response.failed_count == 0

    # ------------------------------------------------------------------
    # 3. Empty list
    # ------------------------------------------------------------------
    empty_response = analyzer.analyze(
        {
            "query": "nothing found",
            "results": [],
        }
    )

    assert empty_response.analyzed_count == 0
    assert empty_response.papers == []

    # ------------------------------------------------------------------
    # 4. Missing abstract: analysis modules still receive the paper;
    #    orchestrator does not invent content.
    # ------------------------------------------------------------------
    no_abstract = {
        **paper,
        "document_id": "126",
        "rank": 1,
        "summary": None,
    }

    no_abstract_result = analyzer.analyze_paper(no_abstract)
    assert no_abstract_result.document_id == "126"

    # ------------------------------------------------------------------
    # 5. Component failure is isolated
    # ------------------------------------------------------------------
    class FailingModule:
        def analyze(self, paper: Any) -> Any:
            raise RuntimeError("simulated module failure")

    partial_analyzer = ResearchPaperAnalyzer(
        summary_analyzer=modules["summary"],
        model_analyzer=FailingModule(),
        dataset_analyzer=modules["dataset"],
        methodology_analyzer=modules["methodology"],
        findings_analyzer=modules["findings"],
        strengths_analyzer=modules["strengths"],
        weaknesses_analyzer=modules["weaknesses"],
    )

    partial = partial_analyzer.analyze_paper(paper)

    assert partial.status == AnalysisStatus.PARTIAL
    assert partial.component_status["model"] == "failed"
    assert partial.model == UNDETERMINABLE_TEXT
    assert partial.summary != UNDETERMINABLE_TEXT

    # ------------------------------------------------------------------
    # 6. All-module failure -> failed paper
    # ------------------------------------------------------------------
    failing_modules = {
        name: FailingModule()
        for name in ResearchPaperAnalyzer.COMPONENTS
    }

    all_failed_analyzer = ResearchPaperAnalyzer(
        summary_analyzer=failing_modules["summary"],
        model_analyzer=failing_modules["model"],
        dataset_analyzer=failing_modules["dataset"],
        methodology_analyzer=failing_modules["methodology"],
        findings_analyzer=failing_modules["findings"],
        strengths_analyzer=failing_modules["strengths"],
        weaknesses_analyzer=failing_modules["weaknesses"],
    )

    failed = all_failed_analyzer.analyze_paper(paper)

    assert failed.status == AnalysisStatus.FAILED
    assert failed.error_message

    # ------------------------------------------------------------------
    # 7. Duplicate IDs are explicit, not silently duplicated
    # ------------------------------------------------------------------
    duplicate_response = analyzer.analyze(
        {
            "query": "duplicate test",
            "results": [
                paper,
                {
                    **paper,
                    "rank": 2,
                },
            ],
        }
    )

    assert duplicate_response.analyzed_count == 2
    assert duplicate_response.papers[1].status == (
        AnalysisStatus.FAILED
    )
    assert "Duplicate document_id" in (
        duplicate_response.papers[1].error_message or ""
    )

    # ------------------------------------------------------------------
    # 8. Invalid input
    # ------------------------------------------------------------------
    try:
        analyzer.analyze(
            {
                "query": "bad",
                "results": [
                    {
                        "rank": 1,
                        "title": "Missing ID",
                        "summary": "text",
                    }
                ],
            }
        )
    except InvalidPaperError:
        pass
    else:
        raise AssertionError(
            "Missing document_id was not rejected."
        )

    # ------------------------------------------------------------------
    # 9. Invalid evidence
    # ------------------------------------------------------------------
    class BadEvidenceModule:
        def analyze(self, paper: Any) -> Any:
            return {
                "value": "bad evidence",
                "evidence": [
                    {"text": "", "source": "abstract"}
                ],
            }

    bad_evidence_analyzer = ResearchPaperAnalyzer(
        summary_analyzer=BadEvidenceModule(),
        model_analyzer=modules["model"],
        dataset_analyzer=modules["dataset"],
        methodology_analyzer=modules["methodology"],
        findings_analyzer=modules["findings"],
        strengths_analyzer=modules["strengths"],
        weaknesses_analyzer=modules["weaknesses"],
    )

    bad_evidence_result = bad_evidence_analyzer.analyze_paper(
        paper
    )

    assert bad_evidence_result.status == AnalysisStatus.PARTIAL
    assert bad_evidence_result.component_status["summary"] == "failed"

    print("ResearchPaperAnalyzer self-test: PASSED")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format=(
            "%(asctime)s | %(levelname)s | "
            "%(name)s | %(message)s"
        ),
    )
    run_self_test()