"""
Pydantic v2 contracts for uploaded-paper question answering.

This module defines DATA CONTRACTS only.

Important architecture:

    LLM structured output
        question = optional provider echo
        evidence = [6, 8, 10]
                    │
                    ▼
        canonical backend question + integer evidence references
                    │
                    ▼
    trusted RAG pipeline evidence
                    │
                    ▼
        QAEvidence objects
                    │
                    ▼
              QAResponse

The LLM is allowed to identify evidence only by numeric reference.
It must NOT manufacture document/chunk/page provenance.

The authoritative provenance objects are produced by the RAG pipeline.
The API layer is responsible for resolving the LLM evidence numbers against
that trusted evidence collection before constructing QAResponse.

This module contains DATA CONTRACTS only. It intentionally contains no RAG,
retrieval, embedding, FAISS, prompt, LLM, PDF, or validation algorithms.
"""

from __future__ import annotations

import math
from enum import Enum
from typing import Any, Mapping, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)

try:
    from backend.schemas.paper import ValidationMetadata, ValidationStatus
except ImportError:
    from schemas.paper import ValidationMetadata, ValidationStatus  # type: ignore


# ---------------------------------------------------------------------------
# Base models
# ---------------------------------------------------------------------------


class _QAModel(BaseModel):
    """
    Shared configuration for API/domain QA models.

    extra='ignore' is intentionally retained for response compatibility.
    Request models use _StrictRequest instead.
    """

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True,
        extra="ignore",
        validate_assignment=True,
    )


class _StrictRequest(_QAModel):
    """Strict configuration for user-controlled request payloads."""

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True,
        extra="forbid",
        validate_assignment=True,
    )


# ---------------------------------------------------------------------------
# Pipeline status
# ---------------------------------------------------------------------------


class QAStatus(str, Enum):
    """Terminal QA states exposed by RAGPipeline."""

    SUCCESS = "success"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------


class QARequest(_StrictRequest):
    """
    One question explicitly scoped to one uploaded research paper.
    """

    document_id: str = Field(min_length=1)
    question: str = Field(min_length=1)
    session_id: Optional[str] = Field(default=None, min_length=1)

    @field_validator("document_id", mode="before")
    @classmethod
    def validate_document_id(cls, value: Any) -> str:
        if not isinstance(value, str):
            raise ValueError("document_id must be a string.")

        value = value.strip()

        if not value:
            raise ValueError(
                "document_id cannot be empty or whitespace."
            )

        return value

    @field_validator("question", mode="before")
    @classmethod
    def validate_question(cls, value: Any) -> str:
        if not isinstance(value, str):
            raise ValueError("question must be a string.")

        value = value.strip()

        if not value:
            raise ValueError(
                "question cannot be empty or whitespace."
            )

        # Preserve scientific terminology and user wording.
        return value

    @field_validator("session_id", mode="before")
    @classmethod
    def validate_session_id(
        cls,
        value: Any,
    ) -> Optional[str]:
        if value is None:
            return None

        if not isinstance(value, str):
            raise ValueError(
                "session_id must be a string when supplied."
            )

        value = value.strip()

        if not value:
            raise ValueError(
                "session_id cannot be empty or whitespace."
            )

        return value


# ---------------------------------------------------------------------------
# Trusted evidence returned by ContextBuilder / RAG pipeline
# ---------------------------------------------------------------------------


class QAEvidence(_QAModel):
    """
    Authoritative evidence/provenance object.

    IMPORTANT:

    This is NOT generated by the LLM.

    It represents trusted evidence originating from the RAG pipeline and
    therefore may contain document/chunk/page/provenance metadata.
    """

    evidence_id: str = Field(min_length=1)
    document_id: str = Field(min_length=1)
    paper_id: Optional[str] = None
    chunk_id: Optional[str] = None

    rank: Optional[int] = Field(default=None, gt=0)
    score: Optional[float] = None
    reranker_score: Optional[float] = None
    retrieval_score: Optional[float] = None

    section: str = Field(min_length=1)

    page: Optional[int] = Field(default=None, gt=0)
    page_end: Optional[int] = Field(default=None, gt=0)

    source_pages: tuple[int, ...] = ()

    title: Optional[str] = None
    text: str = Field(min_length=1)

    source_metadata: Mapping[str, Any] = Field(
        default_factory=dict
    )

    task_type: str = Field(
        default="qa",
        min_length=1,
    )

    section_priority: int = Field(ge=0)
    selection_order: int = Field(ge=0)

    @field_validator(
        "evidence_id",
        "document_id",
        "section",
        "task_type",
        mode="before",
    )
    @classmethod
    def nonempty_required_text(
        cls,
        value: Any,
        info,
    ) -> str:
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"{info.field_name} must be a non-empty string."
            )

        return value.strip()

    @field_validator(
        "paper_id",
        "chunk_id",
        "title",
        mode="before",
    )
    @classmethod
    def optional_text(
        cls,
        value: Any,
        info,
    ) -> Optional[str]:
        if value is None:
            return None

        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"{info.field_name} must be non-empty when supplied."
            )

        return value.strip()

    @field_validator("text", mode="before")
    @classmethod
    def nonempty_evidence_text(cls, value: Any) -> str:
        if not isinstance(value, str) or not value.strip():
            raise ValueError("evidence text cannot be empty.")

        return value.strip()

    @field_validator(
        "score",
        "reranker_score",
        "retrieval_score",
    )
    @classmethod
    def finite_scores(
        cls,
        value: Optional[float],
        info,
    ) -> Optional[float]:
        if value is not None and not math.isfinite(value):
            raise ValueError(
                f"{info.field_name} must be finite."
            )

        return value

    @field_validator("source_pages")
    @classmethod
    def valid_source_pages(
        cls,
        value: tuple[int, ...],
    ) -> tuple[int, ...]:
        if any(page <= 0 for page in value):
            raise ValueError(
                "source_pages values must be >= 1."
            )

        if value != tuple(sorted(set(value))):
            raise ValueError(
                "source_pages must be sorted and unique."
            )

        return value

    @model_validator(mode="after")
    def validate_page_range(self) -> "QAEvidence":
        if (
            self.page is not None
            and self.page_end is not None
            and self.page > self.page_end
        ):
            raise ValueError(
                "page cannot exceed page_end."
            )

        if self.source_pages:
            if (
                self.page is not None
                and self.source_pages[0] != self.page
            ):
                raise ValueError(
                    "source_pages start does not match page."
                )

            if (
                self.page_end is not None
                and self.source_pages[-1] != self.page_end
            ):
                raise ValueError(
                    "source_pages end does not match page_end."
                )

        return self


# ---------------------------------------------------------------------------
# LLM evidence references
# ---------------------------------------------------------------------------


class QAEvidenceReference(_QAModel):
    """
    Backend-compatible rich evidence reference.

    This model is retained for compatibility with older callers that may
    already construct explicit evidence-reference objects.

    NEW QA LLM output MUST use integer evidence references instead:

        "evidence": [6, 8, 10]

    The API/pipeline may later enrich those integers into trusted
    QAEvidence objects.
    """

    evidence_number: int = Field(ge=1)

    chunk_id: Optional[str] = None
    document_id: Optional[str] = None
    paper_id: Optional[str] = None
    page: Optional[int] = Field(default=None, ge=1)
    section: Optional[str] = None

    @field_validator(
        "chunk_id",
        "document_id",
        "paper_id",
        "section",
        mode="before",
    )
    @classmethod
    def optional_reference_text(
        cls,
        value: Any,
        info,
    ) -> Optional[str]:
        if value is None:
            return None

        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"{info.field_name} must be non-empty when supplied."
            )

        return value.strip()


# ---------------------------------------------------------------------------
# Primitive LLM evidence reference
# ---------------------------------------------------------------------------


def _validate_evidence_reference(
    value: Any,
) -> int:
    """
    Validate one LLM evidence reference.

    Important:
        bool is rejected even though bool subclasses int in Python.

    Accepted:
        1
        6
        10

    Rejected:
        True
        False
        0
        -1
        1.5
        "6"
        None
    """

    if isinstance(value, bool):
        raise ValueError(
            "evidence references must be integers, not booleans."
        )

    if not isinstance(value, int):
        raise ValueError(
            "evidence references must be integers."
        )

    if value < 1:
        raise ValueError(
            "evidence references must be >= 1."
        )

    return value


# ---------------------------------------------------------------------------
# Citations generated by RAGPipeline
# ---------------------------------------------------------------------------


class QACitation(_QAModel):
    """
    Exact provenance fields copied/generated by RAGPipeline.
    """

    evidence_index: int = Field(ge=1)

    document_id: Optional[str] = None
    paper_id: Optional[str] = None
    chunk_id: Optional[str] = None

    section: Optional[str] = None
    section_heading: Optional[str] = None

    page: Optional[int] = Field(default=None, ge=1)
    page_end: Optional[int] = Field(default=None, ge=1)

    source_pages: tuple[int, ...] = ()

    rank: Optional[int] = Field(default=None, ge=1)

    score: Optional[float] = None
    retrieval_score: Optional[float] = None
    reranker_score: Optional[float] = None

    label: Optional[str] = None

    @field_validator(
        "document_id",
        "paper_id",
        "chunk_id",
        "section",
        "section_heading",
        "label",
        mode="before",
    )
    @classmethod
    def optional_citation_text(
        cls,
        value: Any,
        info,
    ) -> Optional[str]:
        if value is None:
            return None

        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"{info.field_name} must be non-empty when supplied."
            )

        return value.strip()

    @field_validator(
        "score",
        "retrieval_score",
        "reranker_score",
    )
    @classmethod
    def finite_citation_scores(
        cls,
        value: Optional[float],
        info,
    ) -> Optional[float]:
        if value is not None and not math.isfinite(value):
            raise ValueError(
                f"{info.field_name} must be finite."
            )

        return value

    @field_validator("source_pages")
    @classmethod
    def valid_citation_pages(
        cls,
        value: tuple[int, ...],
    ) -> tuple[int, ...]:
        if any(page <= 0 for page in value):
            raise ValueError(
                "source_pages values must be >= 1."
            )

        if value != tuple(sorted(set(value))):
            raise ValueError(
                "source_pages must be sorted and unique."
            )

        return value

    @model_validator(mode="after")
    def validate_page_range(self) -> "QACitation":
        if (
            self.page is not None
            and self.page_end is not None
            and self.page > self.page_end
        ):
            raise ValueError(
                "page cannot exceed page_end."
            )

        return self


# ---------------------------------------------------------------------------
# Parsed QA output from parser.py / prompts.py
# ---------------------------------------------------------------------------


class QAParsedOutput(_QAModel):
    """
    Exact structured QA generation payload.

    The LLM identifies evidence by numeric reference only.

    Example:

        {
            "question": "What ...?",
            "answer": "...",
            "grounded": true,
            "evidence": [6, 8, 10]
        }

    These numbers refer to evidence items supplied in the RAG context.

    They are NOT provenance objects and MUST NOT be interpreted as
    document/chunk/page metadata.

    Trusted provenance is resolved separately from the pipeline's evidence
    collection.
    """

    # Provider echo is optional at the parser boundary for backward
    # compatibility. The RAG pipeline always injects the trusted API question
    # before constructing the final QAResponse.
    question: Optional[str] = None

    answer: str
    grounded: bool

    # IMPORTANT:
    #
    # Do NOT change this back to:
    #
    #     tuple[QAEvidenceReference, ...]
    #
    # because the current LLM contract emits:
    #
    #     [6, 8, 10]
    #
    # not:
    #
    #     [{"evidence_number": 6}, ...]
    evidence: tuple[int, ...]

    @field_validator("question", mode="before")
    @classmethod
    def validate_question(cls, value: Any) -> Optional[str]:
        if value is None:
            return None

        if not isinstance(value, str):
            raise ValueError("question must be a string when supplied.")

        value = " ".join(value.split()).strip()

        if not value:
            raise ValueError("question cannot be empty when supplied.")

        return value

    @field_validator("answer", mode="before")
    @classmethod
    def validate_answer(cls, value: Any) -> str:
        if not isinstance(value, str):
            raise ValueError("answer must be a string.")

        value = value.strip()

        if not value:
            raise ValueError("answer cannot be empty.")

        return value

    @field_validator("evidence", mode="before")
    @classmethod
    def validate_evidence(
        cls,
        value: Any,
    ) -> Any:
        if value is None:
            raise ValueError(
                "evidence must be a list/tuple of integer references."
            )

        if isinstance(value, (str, bytes)):
            raise ValueError(
                "evidence must be a sequence of integer references."
            )

        try:
            values = list(value)
        except TypeError as exc:
            raise ValueError(
                "evidence must be a sequence of integer references."
            ) from exc

        return tuple(
            _validate_evidence_reference(item)
            for item in values
        )

    @model_validator(mode="after")
    def validate_evidence_numbers(self) -> "QAParsedOutput":
        numbers = self.evidence

        if len(numbers) != len(set(numbers)):
            raise ValueError(
                "evidence reference values must be unique."
            )

        if self.grounded and not numbers:
            raise ValueError(
                "grounded=True requires at least one evidence reference."
            )

        return self


# ---------------------------------------------------------------------------
# Diagnostics / error transport
# ---------------------------------------------------------------------------


class QAError(_QAModel):
    """Serializable PipelineResponse.error payload."""

    code: str = Field(min_length=1)
    message: str = Field(min_length=1)
    reason: Optional[str] = None
    stage: Optional[str] = None
    details: Mapping[str, Any] = Field(
        default_factory=dict
    )


class QADiagnostics(_QAModel):
    """
    Opaque-but-JSON-safe pipeline diagnostics.

    Stage-specific fields remain in `stages` because pipeline.py owns their
    exact timing and diagnostics vocabulary.
    """

    candidate_k: Optional[int] = Field(default=None, ge=1)
    final_k: Optional[int] = Field(default=None, ge=1)

    task_type: str = "qa"
    scope: str = "uploaded"

    session_scoped: bool = False

    candidate_count: Optional[int] = Field(
        default=None,
        ge=0,
    )

    evidence_count: Optional[int] = Field(
        default=None,
        ge=0,
    )

    context_budget_exhausted: Optional[bool] = None

    total_seconds: Optional[float] = None

    insufficient_evidence_reason: Optional[str] = None

    stages: Mapping[str, Any] = Field(
        default_factory=dict
    )

    extra: Mapping[str, Any] = Field(
        default_factory=dict
    )

    @field_validator("total_seconds")
    @classmethod
    def finite_total_seconds(
        cls,
        value: Optional[float],
    ) -> Optional[float]:
        if value is not None:
            if not math.isfinite(value) or value < 0:
                raise ValueError(
                    "total_seconds must be finite and >= 0."
                )

        return value


# ---------------------------------------------------------------------------
# Final QA response
# ---------------------------------------------------------------------------


class QAResponse(_QAModel):
    """
    Frontend/API representation of one evidence-grounded paper-QA result.

    Important distinction:

        structured_output.evidence
            -> integer references selected by the LLM

        evidence
            -> authoritative rich QAEvidence objects from RAG pipeline

        citations
            -> authoritative citation objects from RAG pipeline
    """

    document_id: str = Field(min_length=1)
    question: str = Field(min_length=1)

    answer: Optional[str] = None

    status: QAStatus

    success: bool
    grounded: bool

    # Trusted rich context evidence.
    evidence: tuple[QAEvidence, ...] = ()

    # Trusted pipeline citations.
    citations: tuple[QACitation, ...] = ()

    # Parsed LLM structure.
    #
    # evidence here is intentionally tuple[int, ...].
    structured_output: Optional[QAParsedOutput] = None

    validation: Optional[ValidationMetadata] = None

    diagnostics: Optional[QADiagnostics] = None

    error: Optional[QAError] = None

    @field_validator("document_id", mode="before")
    @classmethod
    def validate_response_document_id(
        cls,
        value: Any,
    ) -> str:
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                "document_id must be a non-empty string."
            )

        return value.strip()

    @field_validator("question", mode="before")
    @classmethod
    def validate_response_question(
        cls,
        value: Any,
    ) -> str:
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                "question must be a non-empty string."
            )

        return value.strip()

    @field_validator("answer", mode="before")
    @classmethod
    def validate_optional_answer(
        cls,
        value: Any,
    ) -> Optional[str]:
        if value is None:
            return None

        if not isinstance(value, str):
            raise ValueError(
                "answer must be a string or null."
            )

        value = value.strip()

        return value or None

    @model_validator(mode="after")
    def enforce_response_integrity(self) -> "QAResponse":
        """
        Enforce final document isolation and status invariants.

        Integer structured evidence references are deliberately NOT checked
        for document IDs here because they contain no provenance.

        Provenance checks happen against trusted QAEvidence/QACitation objects.
        """

        evidence_document_ids = {
            item.document_id
            for item in self.evidence
            if item.document_id
        }

        citation_document_ids = {
            item.document_id
            for item in self.citations
            if item.document_id
        }

        validation_document_ids = set()

        if self.validation is not None:
            for decision in self.validation.claim_decisions:
                if decision.document_id:
                    validation_document_ids.add(
                        decision.document_id
                    )

        for source_name, ids in (
            ("evidence", evidence_document_ids),
            ("citations", citation_document_ids),
            ("validation.claim_decisions", validation_document_ids),
        ):
            mismatched = ids - {self.document_id}

            if mismatched:
                raise ValueError(
                    f"{source_name} contains document IDs inconsistent "
                    f"with response.document_id="
                    f"{self.document_id!r}: "
                    f"{sorted(mismatched)!r}."
                )

        # ---------------------------------------------------------------
        # Structured-output question identity
        # ---------------------------------------------------------------

        if self.structured_output is not None:
            if self.structured_output.question is None:
                raise ValueError(
                    "structured_output.question must be populated by the "
                    "RAG pipeline before constructing QAResponse."
                )

            expected_question = " ".join(self.question.split()).casefold()
            returned_question = " ".join(
                self.structured_output.question.split()
            ).casefold()

            if returned_question != expected_question:
                raise ValueError(
                    "structured_output.question does not match "
                    "response.question."
                )

        # ---------------------------------------------------------------
        # Insufficient evidence state
        # ---------------------------------------------------------------

        if self.status is QAStatus.INSUFFICIENT_EVIDENCE:
            if self.success:
                raise ValueError(
                    "insufficient_evidence cannot have success=True."
                )

            if self.answer is not None:
                raise ValueError(
                    "insufficient_evidence must have answer=null."
                )

            if self.grounded:
                raise ValueError(
                    "insufficient_evidence cannot be grounded=True."
                )

            if self.evidence or self.citations:
                raise ValueError(
                    "insufficient_evidence must not contain "
                    "fabricated evidence/citations."
                )

        # ---------------------------------------------------------------
        # Success state
        # ---------------------------------------------------------------

        if self.status is QAStatus.SUCCESS:
            if not self.success:
                raise ValueError(
                    "success status requires success=True."
                )

            if self.answer is None:
                raise ValueError(
                    "success status requires a non-null answer."
                )

        return self

    @property
    def is_insufficient_evidence(self) -> bool:
        return self.status is QAStatus.INSUFFICIENT_EVIDENCE


# ---------------------------------------------------------------------------
# Compatibility aliases
# ---------------------------------------------------------------------------


QAResult = QAResponse
EvidenceReference = QAEvidenceReference
Citation = QACitation


# ---------------------------------------------------------------------------
# Offline acceptance tests
# ---------------------------------------------------------------------------


def run_self_test() -> None:
    """
    Deterministic schema-only acceptance tests.

    No model, network, FAISS, PDF, or external files are required.
    """

    # ------------------------------------------------------------------
    # 1. Valid request
    # ------------------------------------------------------------------

    request = QARequest(
        document_id="paper_A",
        question="What dataset did the authors use?",
        session_id="session_001",
    )

    assert request.document_id == "paper_A"
    assert request.question == (
        "What dataset did the authors use?"
    )

    # ------------------------------------------------------------------
    # 2-5. Invalid requests
    # ------------------------------------------------------------------

    invalid_requests = (
        {
            "document_id": "paper_A",
            "question": "",
        },
        {
            "document_id": "paper_A",
            "question": "   ",
        },
        {
            "document_id": "",
            "question": "What model was used?",
        },
        {
            "document_id": "   ",
            "question": "What model was used?",
        },
        {
            "question": "What model was used?",
        },
    )

    for payload in invalid_requests:
        try:
            QARequest(**payload)
        except Exception:
            pass
        else:
            raise AssertionError(
                f"Invalid QARequest accepted: {payload!r}"
            )

    # ------------------------------------------------------------------
    # 6. Valid authoritative evidence
    # ------------------------------------------------------------------

    evidence = QAEvidence(
        evidence_id="ev_1",
        document_id="paper_A",
        paper_id="paper_A",
        chunk_id="chunk_17",
        rank=1,
        score=0.91,
        reranker_score=0.88,
        retrieval_score=0.84,
        section="Dataset",
        page=5,
        page_end=5,
        source_pages=(5,),
        title="Example Paper",
        text="The experiments use the XYZ dataset.",
        task_type="qa",
        section_priority=10,
        selection_order=0,
    )

    # ------------------------------------------------------------------
    # 7. Valid citation
    # ------------------------------------------------------------------

    citation = QACitation(
        evidence_index=1,
        document_id="paper_A",
        paper_id="paper_A",
        chunk_id="chunk_17",
        section="Dataset",
        page=5,
        page_end=5,
        source_pages=(5,),
        rank=1,
        score=0.91,
        retrieval_score=0.84,
        reranker_score=0.88,
        label="Example Paper — Dataset, p. 5",
    )

    # ------------------------------------------------------------------
    # 8. CRITICAL:
    #    Current LLM format [6, 8, 10]
    # ------------------------------------------------------------------

    parsed = QAParsedOutput(
        question="What dataset did the authors use?",
        answer=(
            "The paper uses the XYZ dataset. "
            "[Evidence 6]"
        ),
        grounded=True,
        evidence=[6, 8, 10],
    )

    assert parsed.evidence == (6, 8, 10)

    # Parser boundary may accept a missing provider echo; the pipeline must
    # populate it before a final QAResponse is constructed.
    legacy_parsed = QAParsedOutput(
        answer="The paper uses the XYZ dataset.",
        grounded=True,
        evidence=[6],
    )
    assert legacy_parsed.question is None

    # ------------------------------------------------------------------
    # 9. Single integer evidence reference
    # ------------------------------------------------------------------

    single_reference = QAParsedOutput(
        question="What supports the answer?",
        answer="The answer is supported by the paper.",
        grounded=True,
        evidence=[6],
    )

    assert single_reference.evidence == (6,)

    # ------------------------------------------------------------------
    # 10. Duplicate references rejected
    # ------------------------------------------------------------------

    try:
        QAParsedOutput(
            question="Duplicate evidence?",
            answer="Duplicate evidence.",
            grounded=True,
            evidence=[6, 6],
        )
    except Exception:
        pass
    else:
        raise AssertionError(
            "Duplicate evidence references were accepted."
        )

    # ------------------------------------------------------------------
    # 11. Invalid reference values rejected
    # ------------------------------------------------------------------

    invalid_evidence_values = (
        [0],
        [-1],
        [True],
        [False],
        ["6"],
        [1.5],
    )

    for invalid_values in invalid_evidence_values:
        try:
            QAParsedOutput(
                question="Invalid evidence?",
                answer="Invalid evidence.",
                grounded=True,
                evidence=invalid_values,
            )
        except Exception:
            pass
        else:
            raise AssertionError(
                "Invalid evidence reference accepted: "
                f"{invalid_values!r}"
            )

    # ------------------------------------------------------------------
    # 12. Final QA response
    # ------------------------------------------------------------------

    response = QAResponse(
        document_id="paper_A",
        question=request.question,
        answer=parsed.answer,
        status=QAStatus.SUCCESS,
        success=True,
        grounded=True,
        evidence=(evidence,),
        citations=(citation,),
        structured_output=parsed,
    )

    assert response.document_id == "paper_A"
    assert response.question == request.question
    assert response.structured_output is not None
    assert response.structured_output.question == response.question
    assert response.structured_output.evidence == (
        6,
        8,
        10,
    )

    # ------------------------------------------------------------------
    # 13. Question echo is mandatory and preserved
    # ------------------------------------------------------------------

    assert parsed.question == "What dataset did the authors use?"

    try:
        QAParsedOutput(
            question="",
            answer="This must fail.",
            grounded=False,
            evidence=[],
        )
    except Exception:
        pass
    else:
        raise AssertionError(
            "Empty LLM question echo was accepted."
        )

    # ------------------------------------------------------------------
    # 14. Cross-document evidence rejected
    # ------------------------------------------------------------------

    wrong_evidence = evidence.model_copy(
        update={
            "document_id": "paper_B",
        }
    )

    try:
        QAResponse(
            document_id="paper_A",
            question="What dataset did the authors use?",
            answer="Wrong paper evidence.",
            status=QAStatus.SUCCESS,
            success=True,
            grounded=True,
            evidence=(wrong_evidence,),
        )
    except Exception:
        pass
    else:
        raise AssertionError(
            "Cross-document evidence was accepted."
        )

    # ------------------------------------------------------------------
    # 15. Insufficient evidence state
    # ------------------------------------------------------------------

    insufficient = QAResponse(
        document_id="paper_A",
        question=(
            "What was the exact electricity cost of training?"
        ),
        answer=None,
        status=QAStatus.INSUFFICIENT_EVIDENCE,
        success=False,
        grounded=False,
    )

    assert insufficient.is_insufficient_evidence
    assert insufficient.answer is None

    # ------------------------------------------------------------------
    # 16. Serialization
    # ------------------------------------------------------------------

    dumped = response.model_dump()

    assert isinstance(dumped, dict)
    assert dumped["structured_output"]["evidence"] == (
        6,
        8,
        10,
    )

    # Pydantic keeps tuple[int, ...] in Python-mode model_dump().
    # JSON serialization correctly converts the tuple to a JSON array.
    json_dumped = response.model_dump_json()
    assert isinstance(json_dumped, str)

    import json

    decoded = json.loads(json_dumped)

    assert decoded["structured_output"]["evidence"] == [
        6,
        8,
        10,
    ]

    assert decoded["structured_output"]["question"] == (
        "What dataset did the authors use?"
    )

    print("backend/schemas/qa.py self-test: PASSED")


# ---------------------------------------------------------------------------
# Direct execution
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    run_self_test()